name: SM8150 Xiaomi Pad5

on:
  push:
    branches: [ "main", "aloha+kernel_reserv" ]
    paths:
      - 'Platforms/SurfaceDuo1Pkg/Device/xiaomi-nabu/**'
  workflow_dispatch:

env:
  WM_CI_BUILD: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build NOSB uefi for xiaomi pad 5.
        run: bash scripts/ci_setup.sh && ./build_uefi.py -d xiaomi-nabu
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: uefi-images-nabu
          path: Build/*/ci_artifacts
          compression-level: 9
